import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="flex h-screen w-screen flex-col items-center justify-center"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen w-full flex-col items-center justify-between antialiased`}
      >
        <header className="flex h-[200px] w-full flex-col items-center justify-end gap-6 text-[#285298]">
          <h1 className="text-6xl">BFTour</h1>
          <h3 className="text-lg">장애인 맞춤 여행 지원 플랫폼</h3>
        </header>
        {children}
        <footer className="flex h-[100px] w-full items-center justify-center bg-gray-200">
          <p>© 2023 BFTour. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
